model_type: "plain"

paths:
  plain:
    testing_data_path: "/home/sathya/projects/generativeaffect/outputs/preprocessed_data/ravdess_ext_preprocessed_plain_test.pkl"
    training_data_path: "/home/sathya/projects/generativeaffect/outputs/preprocessed_data/ravdess_ext_preprocessed_plain_train.pkl"
  vrnn:
    testing_data_path: "/home/sathya/projects/generativeaffect/outputs/preprocessed_data/ravdess_ext_preprocessed_vrnn_test.pkl"
    training_data_path: "/home/sathya/projects/generativeaffect/outputs/preprocessed_data/ravdess_ext_preprocessed_vrnn_train.pkl"



model:
  plain:
    latent_space_dim: 256
    va_mlp_hidden_dim: 512
    loss_weights:
      face: 1.0
      voice: 1.0
      va: 1.0
    expert_type: "moe"



train:
  plain:
    learning_rate: 0.0001
    optim_betas: [ 0.95, 0.98 ]
    num_epochs: 100
    batch_size: 32
    checkpoint_every: 20
    checkpoint_path: "./"
    save_model: True
    model_save_path: "/home/sathya/projects/generativeaffect/outputs/models/ravdess_mmvae_pretrained_plain.pt"
    stats_save_path: "/home/sathya/projects/generativeaffect/outputs/models/ravdess_mmvae_pretrained_plain_stats.pt"
    seed: 100
    use_cuda: True
    annealing_type: "static"
    cyclical_annealing:
      min_beta: 0.0001
      max_beta: 0.8
      num_cycles: 8
      annealing_percentage: 0.9
    linear_annealing:
      min_beta: 0.001
      max_beta: 1.0
    static_annealing_beta: 0.1

